/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: melaamory (https://sketchfab.com/melaamory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hangers-w-clothes-6df08ef8a8504504911ef520cd870aa8
Title: Hangers W Clothes
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    Pocket_FRONT_7674: THREE.MeshStandardMaterial;
    Material7471: THREE.MeshStandardMaterial;
    Tshirt_FRONT_7678: THREE.MeshStandardMaterial;
    Waist_Belt_FRONT_7670: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/scene.gltf") as GLTFResult;
  return (
    <group {...props} scale={[0.1, 0.1, 0.1]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Pocket_FRONT_7674}
          scale={[0.1, 0.1, 0.1]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Material7471}
          scale={[0.1, 0.1, 0.1]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Tshirt_FRONT_7678}
          scale={[0.1, 0.1, 0.1]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Waist_Belt_FRONT_7670}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
